### ISSUE TITLE
"predefine" as a constructor?

### ISSUE THREAD

**Issue by krlmlr** [cynkra/constructive#195] opened 2023-06-11 05:42 UTC
``` r
igraph <- local({
  ..env.1.. <- new.env(parent = baseenv())
  ..env.1..$me <- list(
    3,
    FALSE,
    c(1, 2, 2),
    c(0, 1, 0),
    NULL,
    NULL,
    NULL,
    NULL,
    list(
      c(1, 0, 1), list(name = "Ring graph", mutual = FALSE, circular = TRUE),
      list(), list(foo = c("a", "b", "c"))
    ),
    ..env.1..
  ) |>
    structure(class = "igraph")
  ..env.1..$igraph <- constructive::.xptr("0x0")
  ..env.1..$.__igraph_version__. <- "1.5.0"
  ..env.1..$myid <- "71239ea8-004c-474d-a799-ef174a2d8853"
  ..env.1..$me
})

library(constructive)
# Why not opts_environment("predefine") ?
# Can we reuse stuff that we already put into that environment?
construct(igraph, opts_environment(predefine = TRUE))
#> ..env.1.. <- new.env(parent = baseenv())
#> ..env.1..$.__igraph_version__. <- "1.5.0"
#> ..env.1..$igraph <- constructive::.xptr("0x0")
#> ..env.1..$me <- list(
#>   3,
#>   FALSE,
#>   c(1, 2, 2),
#>   c(0, 1, 0),
#>   NULL,
#>   NULL,
#>   NULL,
#>   NULL,
#>   list(
#>     c(1, 0, 1), list(name = "Ring graph", mutual = FALSE, circular = TRUE),
#>     list(), list(foo = c("a", "b", "c"))
#>   ),
#>   ..env.1..
#> ) |>
#>   structure(class = "igraph")
#> ..env.1..$myid <- "71239ea8-004c-474d-a799-ef174a2d8853"
#> list(
#>   3,
#>   FALSE,
#>   c(1, 2, 2),
#>   c(0, 1, 0),
#>   NULL,
#>   NULL,
#>   NULL,
#>   NULL,
#>   list(
#>     c(1, 0, 1), list(name = "Ring graph", mutual = FALSE, circular = TRUE),
#>     list(), list(foo = c("a", "b", "c"))
#>   ),
#>   ..env.1..
#> ) |>
#>   structure(class = "igraph")
# I would expect a clear error message here:
# construct(igraph, opts_environment("new_environment"))
# Doesn't seem to finish, endless recursion? An error would be fine too:
# construct(igraph, opts_environment("new_environment", recurse = FALSE))
```

<sup>Created on 2023-06-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by moodymudskipper** [comment] 2023-06-11 10:08
> Why not opts_environment("predefine")

I think I considered it, but it's not really a constructor, it's just a way to avoid recursion issues, and it breaks the general principle in constructive that we build a single piped call.

and in principle different constructors could be used with the "predefine" behavior, though I'm not so sure how it's working atm.

> I would expect a clear error message here:
> construct(igraph, opts_environment("new_environment"))

Indeed, is it a duplicate of #77 ?

**Comment by krlmlr** [comment] 2023-06-11 12:36
A call of the form 

```r
local({
  ..env.1. <- ...
  ...
})
```

still can be considered a single piped call. I'm asking because `predefine = TRUE` overrides all other arguments, so it's a bit weird.

#77 looks similar, yes.

**Comment by moodymudskipper** [comment] 2023-06-11 22:31
I agree that the current behavior is not satisfying, "predefine" as a constructor makes sense to me in hindsight, I'll give it a bit more thought and fix if I don't find a good counter argument.

**Closed** 2024-06-30 08:25 UTC
